development:
  adapter: postgresql
  encoding: unicode
  database: Skills_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: Skills_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Skills_production
  pool: 5